### ISSUE TITLE
Installation links on Microsoft Artifact Registry redirect to bing

### ISSUE THREAD

**Issue by hairmare** [Azure/api-management-self-hosted-gateway#104]
### Report

The helm install link on https://mcr.microsoft.com/en-us/product/azure-api-management/gateway/about seems to redirect to bing.

### Expected Behavior

I'd like some helm install docs

### Actual Behavior

bing 😩 

### Steps to Reproduce the Problem

1. go to https://mcr.microsoft.com/en-us/product/azure-api-management/gateway/about
2. in the usage section click on the Helm install docs: https://aka.ms/apim/sputnik/deploy/apim/sputnik/deploy/k8s/helm
3. be redirected to bing

### Logs from self-hosted gateway

n/a

### Self-hosted Gateway Version

none

### Deployment

Other

### Platform

Any

**Comment by tomkerkhove** [comment]
Deployed already actually.
