### ISSUE TITLE
No analytics for APIs using self-hosted gateway

### ISSUE THREAD

**Issue by SeeSharpCode** [Azure/api-management-self-hosted-gateway#15]
I've deployed a self-hosted gateway to an AKS cluster and have added a couple of APIs to it.

I'm able to successfully call these APIs through the gateway, but those requests don't show up in the analytics for the APIM instance. Is this expected? I've reviewed all of the documentation on self-hosted gateways I could find, and they only mention metrics and Azure Monitor/Logging.

**Comment by vladvino** [comment]
@VitaliyKurokhtin please comment.

**Comment by VitaliyKurokhtin** [comment]
That is correct. At the moment only cloud metrics are available. Logging to Azure monitor is coming. Analytics is not expected to aggregate self-hosted traffic. Replacement functionality will come in future.

**Comment by pjbhakta-outlook** [comment]
Do we have replacement functionality in place now?

**Comment by tomkerkhove** [comment]
Cloud metrics are currently the way forward; we don't have analytics for SHGW.

Tagging @anishtallapureddy who is PM for this
