### ISSUE TITLE
Include self-hosted App Insights for self-hosted gateway

### ISSUE THREAD

**Issue by stinggray** [Azure/api-management-self-hosted-gateway#175]
### Proposal

When running API Management self-hosted gateway, including a self-hosted app insights will ensure visibility, monitoring, and analytics. Please add a self-hosted app insights feature for self-hosted gateway.

### Use-Case

Application Insights is a useful addition to APIM. Adding the self-hosted app insights version will ensure consistency in the current APIM self-hosted and developer portal self-hosted.

**Comment by tomkerkhove** [comment]
Application Insights is already supported today. If you are facing any issues, it's best to contact support.

**Comment by jjasundry** [comment]
> Application Insights is already supported today. If you are facing any issues, it's best to contact support.

Agreed. App Insights functions today. The feature request is for a **self-hosted app insights**. Today, I can run self-hosted APIM and self-hosted developer portal. The missing piece of self-hosted app insights disrupts the option to have a fully self-hosted solution for our internal development teams.

**Comment by tomkerkhove** [comment]
That's a good feature request for the Azure Monitor team, but I'm afraid we will not be able to help with that - Sorry!

**Comment by stinggray** [comment]
Agreed. App Insights functions today. The feature request is for a self-hosted app insights. Today, I can run self-hosted APIM and self-hosted developer portal. The missing piece of self-hosted app insights disrupts the option to have a fully self-hosted solution for our internal development teams.

**Comment by tomkerkhove** [comment]
That's a good feature request for the Azure Monitor team - However, there is not much we can help with from an Azure API Management side.

**Comment by stinggray** [comment]
> That's a good feature request for the Azure Monitor team - However, there is not much we can help with from an Azure API Management side.

I don't see an Azure Monitor team listed here in GitHub. Is there a place to submit this feature request? Also, how will that interaction between Azure Monitor team and self-hosted APIM exchange? If the Azure Monitor team creates a self-hosted feature, but the self-hosted APIM still publishes to the cloud hosted App Insights; the end results is not realized.

**Comment by tomkerkhove** [comment]
You can create feature requests on https://feedback.azure.com/d365community/forum/3887dc70-2025-ec11-b6e6-000d3a4f09d0.

Once that feature is there, we can add it to our backlog to integrate with it; but they have to build it first.

**Comment by stinggray** [comment]
I created a feature request in Azure Monitor as suggested. If others find this thread, feel free to up-vote the request!
https://feedback.azure.com/d365community/idea/1b08c8d1-d165-ed11-a81b-000d3ae49307
