### ISSUE TITLE
Add Support for ingressClassName in Helm Chart

### ISSUE THREAD

**Issue by TimMnz09** [Azure/api-management-self-hosted-gateway#177]
### Proposal

We are running the local gateway in a cluster with multiple ingress-classes deployed.
Currently I can not define the ingressClassName for my api-gateway, so I can not assign the correct ingress controller to my gateway.
K8s Doc: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

Can you make this parameter configurable over the values.yaml?

### Use-Case

No extra configuration for the ingress object in my setup

**Comment by tomkerkhove** [comment]
Feel free to send a pull request, happy to review it :)

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by tomkerkhove** [comment]
This is available in https://github.com/Azure/api-management-self-hosted-gateway/releases/tag/v1.5.2
