### ISSUE TITLE
Support for v2

### ISSUE THREAD

**Issue by oskrabanek** [Azure/api-management-self-hosted-gateway#178]
### Proposal

Although the v1 is marked as obsolete and will be deprecated later this year, the charts have support for V1 only.

### Use-Case

As a developer I want to use helm chart suitable for API Management v2.

**Comment by tomkerkhove** [comment]
This is not correct, the Helm chart works perfectly fine with Configuration API v2 and SHGW v2.

**Comment by tomkerkhove** [comment]
Things are working as expected, closing.
