### ISSUE TITLE
Error when in Internal VNET with [ErrorResolvingHostname]

### ISSUE THREAD

**Issue by bean1117** [Azure/api-management-self-hosted-gateway#193]
### Report

I have an APIM instance running in an Internal VNET. When I install the Hosted Gateway using the provided YAML file I can successfully connect the Gateway to the Instance. Note: I did use the host file to repoint the configuration endpoint  to APIMS internal IP Address. 

However when I use the Helm Chart the Pod starts up for about 70 seconds and then restarts. I can make API calls in that 70 second time frame, but then it goes into a crashloop and is down for good. I am using the HostAlias in the Values file, again to repoint the configuration endpoint to the private IP - This does seem to work, for 70 seconds. I see the following error in the logs several times before crash and before this message 

[DnsDiscoveryFailed], message: Failed to discover external instances on DNS name 000-xx-xx-xx-azure-api-management-gateway-instance-discovery. Details: One or more errors occurred. (Resource temporarily unavailable), source: Neighborhood
[ErrorResolvingHostname]

This Error does not give me enough information to debug any further. 

### Expected Behavior

I would expect to see a more detail message about exactly what FQDN's is missing or something more to go on.

### Actual Behavior

[33m[Warn] 2023-02-2T04:54:07.276 [DnsDiscoveryFailed], message: Failed to discover external instances on DNS name 000-xx-xx-xx-azure-api-management-gateway-instance-discovery. Details: One or more errors occurred. (Resource temporarily unavailable), source: Neighborhood

is 

31m[Error]2023-02-2T04:53:55.258 [ErrorResolvingHostname], exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Runtime.DefaultDnsNameResolver.ResolveAsync(String name, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Pipeline.IO\Dns\DefaultDnsNameResolver.cs:line 26
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 

### Steps to Reproduce the Problem

1. HELM Install with Values File - APIM Internal VNET

### Logs from self-hosted gateway

```
Log Error seen Above
```
[33m[Warn] 2023-02-2T04:54:07.276 [DnsDiscoveryFailed], message: Failed to discover external instances on DNS name 000-xx-xx-xx-azure-api-management-gateway-instance-discovery. Details: One or more errors occurred. (Resource temporarily unavailable), source: Neighborhood

Errors Before
31m[Error]2023-02-2T04:53:55.258 [ErrorResolvingHostname], exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Runtime.DefaultDnsNameResolver.ResolveAsync(String name, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Pipeline.IO\Dns\DefaultDnsNameResolver.cs:line 26
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 

### Self-hosted Gateway Version

2.1.6

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

1.26

### Anything else?

Running in an Ubuntu Box using Minikube

**Comment by ferantoMSFT** [comment]
Thanks for filing this error @bean1117 . So, as of this moment, if you have an internal Azure API Management(inside a vnet without public access) the only way to use the self hosted gateway is to establish a private connection between the Azure API management service and your self hosted gateway(via vpn S2S, express route, vnet peering).  Since the self hosted gateway relies on a configuration endpoint to fetch configuration(normally looks something like <apim-service-name>.configuration.azure-api.net), when using internal mode, this configuration endpoint is no accesible through internet, therefore the self hosted gateway doesn't work correctly.

We are finishing a feature that allows the configuration endpoint to have your own custom domain (for example instead of the default <apim-service-name>.configuration.azure-api.net, you could have something like api.configuration.contoso.com), when this is possible, you would be able to add an additional layer that has a public IP like an application gateway to securely expose just this endpoint to internet, allowing self hosted gateway to communicate to the custom configuration API inside an internal Azure API Management. Stay tuned to our releases we will announce support for custom domains for configuration api v2 and this will enable internal Azure API Management + self hosted gateway.

**Comment by ferantoMSFT** [comment]
@bean1117  Something curious though, is the you were able to call your APIs during 70 seconds. Are you saying the you were able to call your APIs through the selfhosted gateway during the first 70 seconds?

**Comment by bean1117** [comment]
@ferantoMSFT Yes we are able to call our API for until the restart occurs. Also we do have direct connection through express route, and have repointed the configuration endpoint to the private IP.  Like I said this works when using just K8S deployment but fails when using the Helm Chart

**Comment by ferantoMSFT** [comment]
ok, thanks for clarifying, let me investigate a little bit. Will reopen.

**Comment by tomkerkhove** [comment]
@bean1117 Would you mind doing a Helm template, redact things and share it here please? My guess is that the deployment is trying to discover instances of the gateway through the headless service but the DNS is failing.

**Comment by tomkerkhove** [comment]
Can you please specify the output of `helm template` please? This is the same command as if you would be done `helm install` but with `template` instead of `install`.

**Comment by bean1117** [comment]
Gotta, here it is
<pre>
---
# Source: azure-api-management-gateway/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: awd-int-shg-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  gateway-key: "REDACTED"
---
# Source: azure-api-management-gateway/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: awd-int-shg-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
data:
  config.service.endpoint: "Redacted.configuration.azure-api.net"
  telemetry.metrics.cloud: "true"
  telemetry.logs.std: "text"
  telemetry.logs.std.level: "info"
  telemetry.logs.std.color:  "true"
  telemetry.logs.local: "auto"
  telemetry.logs.local.json.endpoint: "127.0.0.1:8888"
  telemetry.metrics.local: "none"
  observability.opentelemetry.enabled: "false"
---
# Source: azure-api-management-gateway/templates/service-instance-discovery.yaml
apiVersion: v1
kind: Service
metadata:
  name: awd-int-shg-azure-api-management-gateway-instance-discovery
  labels:
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    azure.apim.kubernetes.io/notes: "Headless service being used for instance discovery of SHGW"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 4290
      targetPort: rate-limit-dc
      protocol: UDP
      name: rate-limit-discovery
    - port: 4291
      targetPort: dc-heartbeat
      protocol: UDP
      name: discovery-heartbeat
  selector:
      app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
      app.kubernetes.io/component: self-hosted-gateway
      app.kubernetes.io/instance: awd-int-shg
---
# Source: azure-api-management-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: awd-int-shg-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
---
# Source: azure-api-management-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awd-int-shg-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
    app.kubernetes.io/component: self-hosted-gateway
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
      app.kubernetes.io/component: self-hosted-gateway
      app.kubernetes.io/instance: awd-int-shg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: awd-int-shg-azure-api-management-gateway
        app.kubernetes.io/component: self-hosted-gateway
        app.kubernetes.io/instance: awd-int-shg
    spec:
      hostAliases:
        - hostnames:
          - Redacted.configuration.azure-api.net
          ip: 10.24.88.5
      terminationGracePeriodSeconds: 60
      serviceAccountName: default
      containers:
        - name: azure-api-management-gateway
          image: "mcr.microsoft.com/azure-api-management/gateway:2.1.5"
          imagePullPolicy: IfNotPresent
          env:
          - name: runtime.deployment.mechanism
            value: "Helm"
          - name: runtime.deployment.artifact.version
            value: "1.5.3"
          - name: runtime.deployment.artifact.source
            value: "Official"
          - name: runtime.deployment.orchestrator.type
            value: "Kubernetes"
          - name: runtime.deployment.highAvailability.enabled
            value: "false"
          - name: runtime.deployment.dapr.enabled
            value: "false"
          - name: neighborhood.host
            value: awd-int-shg-azure-api-management-gateway-instance-discovery
          - name: config.service.auth
            valueFrom:
              secretKeyRef:
                name: awd-int-shg-azure-api-management-gateway
                key: gateway-key
          envFrom:
          - configMapRef:
              name: awd-int-shg-azure-api-management-gateway
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
              # Container port used for rate limiting to discover instances
            - name: rate-limit-dc
              protocol: UDP
              containerPort: 4290
              # Container port used for instances to send heartbeats to each other
            - name: dc-heartbeat
              protocol: UDP
              containerPort: 4291
          readinessProbe:
            httpGet:
              path: /status-0123456789abcdef
              port: http
          livenessProbe:
            httpGet:
              path: /status-0123456789abcdef
              port: http
          resources:
            {}
---
# Source: azure-api-management-gateway/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "awd-int-shg-azure-api-management-gateway-test-connection"
  labels:
    app.kubernetes.io/name: azure-api-management-gateway
    helm.sh/chart: azure-api-management-gateway-1.5.3
    app.kubernetes.io/instance: awd-int-shg
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['awd-int-shg-azure-api-management-gateway:']
  restartPolicy: Never
</pre>

**Comment by tomkerkhove** [comment]
Hm odd; do you use network restrictions inside the Kubernetes cluster or so? Basically, the container is trying to reach the `awd-int-shg-azure-api-management-gateway-instance-discovery` service

**Comment by bean1117** [comment]
@tomkerkhove Thanks for the suggestion. Quick update we moved to a production cluster and I don't see the issue at all. The environment I was seeing the issue was Minikube. So at this point it must be something configured differently in that environment.  I appreciate the troubleshooting help.

**Comment by tomkerkhove** [comment]
Happy to help!

**Comment by pablogorosito** [comment]
I'm having the same issue as well.
Some weird facts:
1- It was working fine until I add another nodepool into the AKS cluster.
2- The new nodepool was for spot nodes.
3- Now I'm having this issue on the default nodepool (the one that has been always working fine)
4- If I force the deployment to run the pod in the spot nodepool it works OK no issues at all.
5- Both nodepools are exactly the same. (same SKUs, same OS, same disk, etc)

**Comment by tomkerkhove** [comment]
Hi, can you please open a support ticket to help you?
