### ISSUE TITLE
Request size limit

### ISSUE THREAD

**Issue by zateckar** [Azure/api-management-self-hosted-gateway#20]
Self-Hosted gateway has rather small request size limit (approx. 20MB) in comparison with an Azure instance (hundreds of MBs, probably constrained by timeout).

How can we increase this limit?

Thank you
Radim

From tracelog:
{
"source": "request-forwarder",
"timestamp": "2020-10-16T09:05:41.7063803Z",
"elapsed": "00:00:00.1742902",
"data": {
"messages": ["**Request body too large.**"]
}
}

**Comment by vladvino** [comment]
@maksimkim please take a look.

**Comment by laboremus777** [comment]
Is there any ETA on the fix? 
We've hit the same problem and that's a major bummer. We have a lot riding on this solution and will really appreciate if updated version could be made available sooner than later.

**Comment by maksimkim** [comment]
This was fixed in 2.0.0
