### ISSUE TITLE
How much traffic can Self Hosted Gateway realistically support?

### ISSUE THREAD

**Issue by chrislangston** [Azure/api-management-self-hosted-gateway#21]
We are evaluating Self Hosted Gateway for our on-premise needs.  

I realize this is a Docker image and throughput is impacted by many factors.  

Can you provide any rough estimates/guidance on how many requests a single Self-Hosted Gateway can support?

I know the Azure pricing documentation shows 4,000 requests/sec.

Thanks,

Chris

**Comment by vladvino** [comment]
@maksimkim how would you answer this question?

**Comment by chrislangston** [comment]
> @maksimkim how would you answer this question?

Hi @vladvino  and @maksimkim, any thoughts on how I can answer this question for our client wanting to use Self Hosted on-premise?

**Comment by zateckar** [comment]
Hi, our 2vCPU/7GB VM handles around 1500 req/s (health checks: no policy or backend; behind F5 balancer and firewall). 

It seems to be scaling well with additional vCPU.

Regards,
Radim

**Comment by chrislangston** [comment]
> Hi, our 2vCPU/7GB VM handles around 1500 req/s (health checks: no policy or backend; behind F5 balancer and firewall).
> 
> It seems to be scaling well with additional vCPU.
> 
> Regards,
> Radim

Thanks @zateckar for the feedback and information.
