### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by oskrabanek** [Azure/api-management-self-hosted-gateway#219]
### Report

According to the consumption in AKS it seems the API Management Self-Hosted Gateway image has a memory leak.
According to the AKS metrics the memory consumption is raising all the time regardless the load see charts below for 3 Azure region for the last 14 days.
![image](https://github.com/Azure/api-management-self-hosted-gateway/assets/6212595/973cea35-1e88-4279-abf0-fe3cb3dd57a5)
Here you can see the request count in the same period for all regions in one chart.
![image](https://github.com/Azure/api-management-self-hosted-gateway/assets/6212595/5446e861-539a-4d47-9f46-f0934a7928ac)

Even though the request counts are totally different, the memory consumption is constantly increasing.

### Expected Behavior

The memory consumption correlates with the load and doesn't increase during the stable load.

### Actual Behavior

Memory consumption increases even during the decreasing load

### Steps to Reproduce the Problem

1. Run the container with constant load for significant amount of time (e.g. 1 day)

### Logs from self-hosted gateway

None

### Self-hosted Gateway Version

2.2.0

### Deployment

Self-Managed (YAML/Helm)

### Platform

Microsoft Azure

### Kubernetes Version

1.25

**Comment by tomkerkhove** [comment]
Thanks for reporting! However, for performance issues we recommend [creating an Azure Support ticket](https://ms.portal.azure.com/#view/Microsoft_Azure_Support/HelpAndSupportBlade/~/overview) instead. They will help you get to the bottom of this and get the info that we need.

Thank you.
