### ISSUE TITLE
Extend CI to deploy & test gateway

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-self-hosted-gateway#25]
Extend CI to deploy the Helm chart on a Kind cluster and call an operation once it's up and running.

However, this would require an Azure API Management instance that has a gateway available.

**Comment by tomkerkhove** [comment]
@vladvino Thoughts on this?

**Comment by vladvino** [comment]
@tomkerkhove neutral to positive😀Did anyone ask for this?

**Comment by tomkerkhove** [comment]
No, just me but it's to guarantee that the Helm chart still works during PRs!

**Comment by tomkerkhove** [comment]
Done in #47
