### ISSUE TITLE
Breaking Change in v1.7.4 destroys ingress

### ISSUE THREAD

**Issue by TimMnz09** [Azure/api-management-self-hosted-gateway#253]
### Report

When Patching from v1.7.3 to v1.7.4 I recognized a breaking change in the helm chart, as no ingress objects have been generated.

Commit: https://github.com/Azure/api-management-self-hosted-gateway/commit/a1d6121a8c3e7873e6179d27bea3152013169016#diff-ec7c49c5de6da78a104c25f6f925d84d131461a2479fdf456f130b88c5951395

ingress has been replaced by ingresscontroller class.

### Expected Behavior

I am running API Gateway with a custom ingress in front of it.

### Actual Behavior

v1.7.4 does not let you configure an `Ingress` object, but only `IngressClass`

### Steps to Reproduce the Problem

1. Configure ingress in v1.7.3
2. Upgrade installation to v1.7.4

### Logs from self-hosted gateway

```
no logs
```

### Self-hosted Gateway Version

2.3.4

### Deployment

OnPremises K8s

### Platform

Other

### Kubernetes Version

1.26

**Comment by tomkerkhove** [comment]
Aah, right. I forgot this change was already in and should have been 2.0 :) Sorry about that.

Ingress resource should not be part of our Helm chart and should be created separately. I'll update the release notes later today
