### ISSUE TITLE
Expired token - self-hosted instance returns 200 empty response

### ISSUE THREAD

**Issue by cermakp** [Azure/api-management-self-hosted-gateway#287]
### Report

In case the self-hosted GW instance has defined expired token, pod is started with the error in the log:

<img width="1265" alt="image" src="https://github.com/Azure/api-management-self-hosted-gateway/assets/49719500/0b275e57-1371-405a-9355-f9be0b132f3b">

However, the pod itself is in a 'Running' state

<img width="530" alt="image" src="https://github.com/Azure/api-management-self-hosted-gateway/assets/49719500/e87e9a79-91a4-4b93-ae21-762dbb0a3531">

When there is a request to such a self-hosted instance, it returns a response with an empty body and 200 response code which is quite confusing

<img width="1195" alt="image" src="https://github.com/Azure/api-management-self-hosted-gateway/assets/49719500/9355407a-ac7b-4e6a-bd41-04a298d5a1f0">

### Expected Behavior

There are 2 options:

1. The instance pod will not start at all  - the same behavior as in the case of not properly loaded configurations
2. The instance will return a response with a 503 response code to any requests

### Actual Behavior

Response with an empty body and 200 response code is returned

### Steps to Reproduce the Problem

1. Configure expired token for the pod running in AKS
2. Start the pod

### Logs from self-hosted gateway

```
example
```

### Self-hosted Gateway Version

2.5.0.0

### Deployment

Self-Managed (YAML/Helm)

### Platform

Microsoft Azure

### Kubernetes Version

Other

**Comment by tomkerkhove** [comment]
What endpoint are you consuming that responds 200? 

You may want to use 2.6.0 where this behavior has changed, it should start up but maybe the 200 will still be there. Do you have a local backup enabled?

**Comment by cermakp** [comment]
Hi @tomkerkhove, 

call to any endpoint exposed on the gateway returned 200 with the empty body. We have plenty of custom endpoints exposed there.

However, based on your advice, we tried the same on version 2.6.0. The gateway startup logic has been completely changed, so right now the gateway is not started at all with the invalid token. As we can see in the logs, a gateway with an invalid token is not able to download the configuration from the managed instance - which is the expected behavior.

**Comment by cermakp** [comment]
I am closing the issue as it has been resolved in version 2.6.0
