### ISSUE TITLE
Latest Version (v1.11.0) of chart not yet available

### ISSUE THREAD

**Issue by TimMnz09** [Azure/api-management-self-hosted-gateway#300]
### Report

It seems like the new version of the helm-chart is not yet available on the artifact hub.
https://artifacthub.io/packages/helm/azure-api-management/azure-api-management-gateway

### Expected Behavior

Whenever a new release is published to new version should be available

### Actual Behavior

Current version 1.11.0 is not yet available 

### Steps to Reproduce the Problem

1. go to https://artifacthub.io/packages/helm/azure-api-management/azure-api-management-gateway
2. look for the version 1.11.0

### Logs from self-hosted gateway

not relevant

### Self-hosted Gateway Version

2.7.0

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

Other

**Comment by pauska** [comment]
The new chart version is visible now

**Comment by tomkerkhove** [comment]
I've missed this issue, this was a sloppy release on my part - sorry!
