### ISSUE TITLE
SHGW request logs disappear after turning on content validation

### ISSUE THREAD

**Issue by R8iKKo** [Azure/api-management-self-hosted-gateway#307]
### Report

Hi,

I recently discovered that after I turn on global content validation, self-hosted gateway stops logging requests after about 2-4 hours after turning on validation. 

I have local diagnostics turned on, everything's working fine until I implement content validation policy. Then after few hours, all request logs disappear. 

Complete setup:

Self-hosted gateway running on Azure Stack Ubuntu 24.01 LTS VM.
gw hosted in podman container.
log settings are localsyslog in json.

exact policy implemented:

```
<validate-content unspecified-content-type-action="detect" max-size="8192" size-exceeded-action="ignore" errors-variable-name="requestBodyValidation">
	<content type="application/json" validate-as="json" action="detect" />
	<content type="text/plain" validate-as="json" action="detect" />
	<content type="application/xml" validate-as="xml" action="detect" />
	<content type="application/soap+xml" validate-as="soap" action="detect" />
	<content type="text/xml" validate-as="soap" action="detect" />
</validate-content>
```

### Expected Behavior

`{\"isRequestSuccess\":true,\"totalTime\":108,\"category\":\"GatewayLogs\",\"callerIpAddress\":\"10.89.1.60\",\"timeGenerated\":\"2024-09-12T06:29:10.6484728Z\",\"region\":\"Czech Republic\",\"correlationId\":\"xxx-xxx-xxx-xxx\",\"method\":\"GET\",\"url\":\"https://example.com/API\",\"backendResponseCode\":200,\"responseCode\":200,\"responseSize\":297,\"cache\":\"none\",\"backendTime\":107,\"apiId\":\"data-provider\",\"operationId\":\"getModifications\",\"productId\":\"data-provider\",\"apimSubscriptionId\":\"xxxxx-xxxx-xxxx-xxxxx\",\"clientProtocol\":\"HTTP/1.1\",\"backendProtocol\":\"HTTP/1.1\",\"apiRevision\":\"10\",\"clientTlsVersion\":\"1.2\",\"backendMethod\":\"GET\",\"backendUrl\":\"https://example.com/backend\",\"lastError\":{\"source\":\"validate-content\",\"reason\":\"ContentTypeNotDefined\",\"message\":\"Unspecified content type  is not allowed.\",\"scope\":\"global\",\"section\":\"inbound\"}}
`
### Actual Behavior

```
{
  "level": "Informational",
  "message": "5",
  "timestamp": "2024-09-12T08:03:56.9180898Z"
}
```

### Steps to Reproduce the Problem

1. Implement any validate-content policy
2. Wait few hours - approx. 2-4 usually
3. Request logs disappears locally, only some kind of telemetry appears.

### Logs from self-hosted gateway

```
{
  "level": "Informational",
  "message": "5",
  "timestamp": "2024-09-12T08:03:56.9180898Z"
}
```

### Self-hosted Gateway Version

2.7.1

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

None

**Comment by tomkerkhove** [comment]
Hi, can you please open a support ticket?

**Comment by R8iKKo** [comment]
Hi, if you mean official ticket on Azure Portal, sure I will do.
