### ISSUE TITLE
Are graphQL endpoints behind self hosted gateway GA?

### ISSUE THREAD

**Issue by jblaaa-codes** [Azure/api-management-self-hosted-gateway#318]
### Discussed in https://github.com/Azure/api-management-self-hosted-gateway/discussions/317

<div type='discussions-op-text'>

<sup>Originally posted by **jblaaa-codes** November 26, 2024</sup>
I see graphQL endpoints added on v2.5.0 #271  in public preview. Is it still in public preview or GA? Thank you.</div>

**Comment by tomkerkhove** [comment]
Duplicate of https://github.com/Azure/api-management-self-hosted-gateway/discussions/317 and not a bug
