### ISSUE TITLE
List Helm Charts on hub.helm.sh

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-self-hosted-gateway#4]
As of today, only my old Helm chart [is listed on hub.helm.sh](https://hub.helm.sh/charts?q=azure-api-managem).

I'm more than happy to work on getting the official one listed.

**Comment by tomkerkhove** [comment]
@miaojiang @vladvino Ok for you if I kick this off?

**Comment by vladvino** [comment]
I don't see why not!
