### ISSUE TITLE
List Helm Charts on CNCF's Artifact Hub

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-self-hosted-gateway#5]
List Helm Charts on CNCF's Artifact Hub - This is becoming the home for all artifact types.

https://artifacthub.io/

**Comment by tomkerkhove** [comment]
For more info, see https://thenewstack.io/cncf-launches-a-one-stop-hub-for-kubernetes-packages/

Took the liberty of creating an org and listing it:
![image](https://user-images.githubusercontent.com/4345663/81375576-1b2b3500-9102-11ea-8794-b12b381f7019.png)

Available on: https://artifacthub.io/package/chart/azure-api-management/azure-api-management-gateway

@vladvino if you create an account I can transfer ownership to you.

**Comment by tomkerkhove** [comment]
@vladvino Feel free to let me know if you want me to transfer it.

**Comment by vladvino** [comment]
@tomkerkhove I signed up using my GitHub account.

**Comment by tomkerkhove** [comment]
Great, invite sent!

**Comment by vladvino** [comment]
Received and accepted!
