### ISSUE TITLE
Json logging

### ISSUE THREAD

**Issue by Andrei-Predoiu** [Azure/api-management-self-hosted-gateway#72]
### Proposal

Hi, 
Given that the gateway is self hosted ,we would really appreciate the ability to enable standardized json logging, as well as have the ability to enable (open) tracing/telemetry for the gateway.

### Use-Case

I want to parse and monitor the logs generated by the self hosted gateway. It is much harder to do so when they are not Json.
I want to enable end to end tracing for calls going through the gateway. Adding Open Telemetry support would enable this

**Comment by tomkerkhove** [comment]
Good to hear you've found your way to our docs! I opened #73 to simplify this for you.

**Comment by Andrei-Predoiu** [comment]
Thanks, i still haven't figured out how to disable colors so that our log management doesn't get confused. If you know i'd appreciate it.

**Comment by tomkerkhove** [comment]
Can you elaborate on that please?

**Comment by Andrei-Predoiu** [comment]
I am using the following log config:
```
  telemetry.logs.std: json
  telemetry.metrics.cloud: "true"
  telemetry.metrics.local: statsd
  telemetry.metrics.local.statsd.endpoint: [redatcted]
  telemetry.metrics.local.statsd.sampling: "1"
  telemetry.metrics.local.statsd.tag-format: dogStatsD
```
The logs look good when i print them out but the ANSI color codes are not understood by our log management and end up being unparsable. The easy solution would be to disable log colors but there is no configuration for that.

![image](https://user-images.githubusercontent.com/5424946/155487933-e671d7bb-6434-4b0a-a8f9-60fdba63b98c.png)

![image](https://user-images.githubusercontent.com/5424946/155488228-f5e78d91-7a51-426d-902b-919b739b5da9.png)

**Comment by tomkerkhove** [comment]
We don't explicitly use log colors, are you sure this is not because of the CLI client that you are using?

**Comment by Andrei-Predoiu** [comment]
That's very strange, i'm running it on kubernetes and i'm not doing anything special.
I think maybe it's because of this: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.console.loggercolorbehavior?view=dotnet-plat-ext-6.0
But i honestly have no idea.

**Comment by tomkerkhove** [comment]
We are not using that at the moment. Are you sure that it is related to the color or the format as such?

**Comment by Andrei-Predoiu** [comment]
It's the ANSI color, if you look at the photo, you can see `[31m` before the json and `[0m` at the end. 
Logs in the console are different colors; Info is white, warn is yellow and errors are red. Logs in datadog start with different  characters depending on the log level also.

This is why my conclusion is that it is the color of the logs.

![image](https://user-images.githubusercontent.com/5424946/155534660-7ccce521-069c-4b52-8edd-f186b2c5dc92.png)

**Comment by tomkerkhove** [comment]
Oh now I see it - Sorry, would you mind opening a dedicated issue for this please?
