### ISSUE TITLE
Add option to disable Log colors

### ISSUE THREAD

**Issue by Andrei-Predoiu** [Azure/api-management-self-hosted-gateway#78]
### Proposal

By default, the self hosted GW produces colored logs. 
It seems like it might not be intended behavior according to this [issue](https://github.com/Azure/api-management-self-hosted-gateway/issues/72#issuecomment-1049871433)

### Use-Case

Logging frameworks have a hard time parsing logs with color codes, as seen here:
[issue](https://github.com/Azure/api-management-self-hosted-gateway/issues/72#issuecomment-1049871433)

**Comment by Andrei-Predoiu** [comment]
@tomkerkhove is this fine?

**Comment by tomkerkhove** [comment]
Certainly, thank you!
