### ISSUE TITLE
Capability to add PersistentVolumeClaim for configuration backup using helm chart

### ISSUE THREAD

**Issue by codesometech** [Azure/api-management-self-hosted-gateway#81]
### Proposal

Capability to add PersistentVolumeClaim for configuration backup using helm chart.

https://docs.microsoft.com/en-us/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production#configuration-backup

### Use-Case

Configure a local storage volume for the self-hosted gateway container, so it can persist a backup copy of the latest downloaded configuration. If connectivity is down, the storage volume can use the backup copy upon restart.

**Comment by tomkerkhove** [comment]
Fair request!

**Comment by LDL-GH** [comment]
@tomkerkhove I created a PR for this issue, mind taking a look?
