### ISSUE TITLE
Security requirements not clear for v2.0.0 on K8S

### ISSUE THREAD

**Issue by tobymilne-haven** [Azure/api-management-self-hosted-gateway#82]
### Report

Hi,
We run several on prem gateways in kubernetes. They are set to use the latest version, and when we refreshed them today they failed to start.

Error is : "Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle"

Rolling back to v 1.2.5 works, so it looks like we are having a problem with the new v2.0.0.

Is there anything we need to do to start using version 2?

Thanks,
Toby

### Expected Behavior

APIM Gateway should start on a read only container

### Actual Behavior

Error is : "Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle"

### Steps to Reproduce the Problem

1. Create on Prem gateway on the api management page
2. Download kubernetes deployment, and set readOnlyFileSystem: true
3. Deploy kubernetes manifest.

### Logs from self-hosted gateway

Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle

### Self-hosted Gateway Version

2.0.0

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

1.18

### Anything else?

Running on AWS EKS.

**Comment by tomkerkhove** [comment]
Thanks for reporting, we are still working on making an announcement that would help but can you share a bit more on how you deploy the gateway?

Do you enforce security policies? We require linux user with 1001 at least

**Comment by tobymilne-haven** [comment]
Hi, thanks for responding quickly!
Yes we deploy the gateway on AWS EC2 instances running EKS, and we have an admissions controller that enforces some policies (known docker registries, non root), but the k8s pod security policy is allowing everything.
We also have an init-container in the gateway deployment to get a fresh auth token from Azure at startup.

For the Gateway, with v1, I have been adding this section to the deployment yaml:

```
containers:
  securityContext:
            runAsNonRoot: true
            runAsUser: 1000 
            readOnlyRootFilesystem: true

```
Which caused the above error on v2. If i set the user to 1001  I still get the error, i need to specify user 1001 and read only false to get the container to start. I'm guessing the CA Cert bundle is getting updated somewhere in the initialisation.

I'd rather run the gateways non root & read only fs if we can - but appreciate that may not be a supported setup.

Thanks,
Toby

**Comment by tobymilne-haven** [comment]
Yep I will set our containers up with that security context. 
I'll keep an eye out for the migration guide.

**Comment by jochenvw** [comment]
Hi - we're also trying to deploy the self-hosted gw but on OpenShift. Same error message when using the default yml:
`Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle` 

After adding
```
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: false
```
We get: 
```
forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000670000, 1000679999], provider "nonroot":
```

Not super deep into containers and orchestrators, but I think this is because OpenShift is more restricted in terms of security than 'vanilla' K8S or AKS. 

Any tips on solving this on OpenShift?

**Comment by tomkerkhove** [comment]
Sorry, I was on paternity leave - Did you manage to figure this out?

**Comment by stfnbstl** [comment]
> Hi Toby,
> 
> We, unfortunately, can't support that due to our CA cert bundling, this is what should be configured at least:
> 
> ```yaml
> securityContext:
>   runAsNonRoot: true
>   runAsUser: 1001
>   readOnlyRootFilesystem: false
> ```
> 
> This will show up in our migration guide as well.

We're also trying to upgrade from 1.2.5 to 2.0.2 but even with your suggestion I get this error:

```
Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle
```

Has anyone already made progress with this issue?

**Comment by npigniergeodis** [comment]
Hi @stfnbstl, what we did on our Openshift Cluster :

1. create a dedicated service account, for ex. "apim-shg-sa"
1. give this sa the anyuid security context constraint for the namespace where you deploy your self-hosted gateway (command to be run by your cluster admin) : 
   `oc adm policy add-scc-to-user anyuid -z apim-shg-sa --namespace <your namespace>`
1. in your deployment, add "serviceAccountName: apim-shg-sa"
![image](https://user-images.githubusercontent.com/26485524/166879303-b751625a-5d07-4fa4-a8de-c9a6c756e618.png)

**Comment by tomkerkhove** [comment]
A patch for this is coming soon as well

**Comment by tomkerkhove** [comment]
`:2.0.3` is out and allows you to deploy as following:
```yml
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001       # This is a built-in user, but you can use any user ie 1000 as well
  runAsGroup: 2000      # This is just an example
  privileged: false
  capabilities:
    drop:
    - all
```

Using read-only filesystem, however, is not supported.

Docs are going to be updated on https://docs.microsoft.com/en-us/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production with a security section but deployment is pending.

**Comment by tomkerkhove** [comment]
I'm going to close it but feel free to re-open in case of issues.

**Comment by npigniergeodis** [comment]
when deploying on our Openshift v4.9 there are some errors, certainly due to the cluster security setup, so on my side I'll stick with my previous solution (a dedicated service account)

error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): 
unknown field "**allowPrivilegeEscalation**" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): 
unknown field "**capabilities**" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): 
unknown field "**privileged**" in io.k8s.api.core.v1.PodSecurityContext]

**Comment by tomkerkhove** [comment]
The above is just an example though, so if you want you can just run it with this (for example)

```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: <your user id>
```

**Comment by npigniergeodis** [comment]
Ok, it works with :
```
securityContext:
  runAsNonRoot: true
  runAsUser: 1002420005
```

the user id 1002420005 is given by a previous error, ( when using `runAsUser: 1001`)
```
[...] spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1002420000, 1002429999] [...]
```

So I picked a user in the proposed range :-)

**Comment by tomkerkhove** [comment]
That's because you are using OpenShift I presume?

**Comment by npigniergeodis** [comment]
> That's because you are using OpenShift I presume?
Yes, Openshift v4.8

**Comment by tomkerkhove** [comment]
Docs are live: https://docs.microsoft.com/en-us/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production#security
