### ISSUE TITLE
Provide capability to use an existing Kubernetes secret for the gateway.auth.key

### ISSUE THREAD

**Issue by LDL-GH** [Azure/api-management-self-hosted-gateway#84]
### Proposal

Right now we need to input the gateway.auth.key as a value in the helm chart. And the secret is created by the helm chart
However it would be nice to also be able to reference an existing secret. 

### Use-Case

This way the secret value can be managed separately from the helm chart.
Also the key is not visible, only the secret name.

**Comment by tomkerkhove** [comment]
@ldl-gh I'm going to cut a release, are you planning on contributing this later on or should I wait?

**Comment by LDL-GH** [comment]
@tomkerkhove  Looking at it right now, I'll let you know where I stand in an hour

**Comment by tomkerkhove** [comment]
Sounds good, thank you!

**Comment by LDL-GH** [comment]
@tomkerkhove  PR is ready for review.
Just in time I hope?

**Comment by tomkerkhove** [comment]
Certainly, thank you!
